### ISSUE TITLE
Replace Confirmation Email with template

### ISSUE THREAD

**Issue by tayormi** [codeclannigeria/codeclannigeria-backend#130]
**Is your feature request related to a problem? Please describe.**
Email Confirmation looks crappy at the moment

**Describe the solution you'd like**
Replace with Email template located at 
https://github.com/codeclannigeria/CodeClanUI/blob/master/email.html
- Email needs to have a subject "Verify Your Email"
- Email should be from Code Clan Nigeria

**Comment by ofuochi** [comment]
Something's still missing on this template. There's no link to where the user will click to verify email.
@rammyblog you need to provide that. 
@tayormi you need to assist Rammy here

**Comment by tayormi** [comment]
Oh. Let me get someone to do it.
@Emmriz, we need you to provide a Verification Email. Use the tool you used the last time to design it.
The email should include a button for users to use to verify their email.

**Comment by ofuochi** [comment]
@tayormi the email template is fine. What I'm talking about is the link to verify email. Url (client base URL and stuff) that will be embedded in the link

**Comment by tayormi** [comment]
Oh. Sorry. We do have it already in the email you are sending to users na. People has been able to verify their emails already just that it doesnt come with a template.

**Comment by ofuochi** [comment]
okay
