### ISSUE TITLE
Allow Formatted Text

### ISSUE THREAD

**Issue by tayormi** [codeclannigeria/codeclannigeria-backend#133]
**Is your feature request related to a problem? Please describe.**
When creating task, it will look unformatted when showing plain text to users. 

**Describe the solution you'd like**
Allow formatted text to be passed and return formatted text on get task.

**Comment by ofuochi** [comment]
this needs more clarification. do you mean allowing HTML?

**Comment by tayormi** [comment]
@ofuochi, yes please. We will want to format the task contents very well so user can be able to understand what they've been told to do.
