### ISSUE TITLE
Return more data for Mentors

### ISSUE THREAD

**Issue by rammyblog** [codeclannigeria/codeclannigeria-backend#136]
**Is your feature request related to a problem? Please describe.**
We need more /profile/mentors to return more info about the mentor. I.e city, county, description and phone number

**Comment by rammyblog** [comment]
@ofuochi  

We need more /profile/mentees to return more info about the mentees. I.e track and email

**Comment by ofuochi** [comment]
@rammyblog what is missing? We've currently returned almost everything

**Comment by rammyblog** [comment]
The mentor email is not returned in  /profile/mentors.
