### ISSUE TITLE
Return more data for Mentees

### ISSUE THREAD

**Issue by rammyblog** [codeclannigeria/codeclannigeria-backend#141]
**Is your feature request related to a problem? Please describe.**
We need more /profile/mentees to return more info about the mentees. I.e track and email

**Comment by rammyblog** [comment]
/profile/mentees is still not returning track info

**Comment by rammyblog** [comment]
/profile/mentees is still not returning track and email

**Comment by ofuochi** [comment]
@rammyblog check and close
