### ISSUE TITLE
Cannot Create a Stage

### ISSUE THREAD

**Issue by tayormi** [codeclannigeria/codeclannigeria-backend#147]
**Describe the bug**
Go this Error on Creating a stage
`{
  "message": [
    "level must be an integer number",
    "level must not be less than 0"
  ],
  "error": "Bad Request",
  "stack": null,
  "errors": null,
  "path": "/stages",
  "timestamp": "2020-08-28T09:24:58.138Z",
  "statusCode": 400,
  "status": "BAD_REQUEST"
}`

**To Reproduce**
Use this request.
`{
  "track": "5efe68cf1506ab00179f641a",
  "title": "Basic HTML",
  "description": "Learn HTML",
  "taskCount": 4
}`

**Expected behavior**
I should be able to create a Stage

**Comment by ofuochi** [comment]
The error message is clear. You're aren't passing level.
Check the swagger doc for the contract
