### ISSUE TITLE
Mentee Submissions not returning data

### ISSUE THREAD

**Issue by rammyblog** [codeclannigeria/codeclannigeria-backend#157]
**Describe the bug**
/mentors/submissions does not return any data but returns the total count.

![image](https://user-images.githubusercontent.com/36502131/92478268-d3b0d480-f1d9-11ea-92eb-130304a0e8bc.png)

**Comment by rammyblog** [comment]
/mentors/submissions does not return any data at all for the mentor.
I submitted a task now, and when I visited the endpoint  /mentors/submissions nothing came back

**Comment by ofuochi** [comment]
this works. this you test it?
