### ISSUE TITLE
[FEAT] User Roles

### ISSUE THREAD

**Issue by ofuochi** [codeclannigeria/codeclannigeria-backend#24]
There should be 3 main user roles; `Mentee`, `Mentor`, `Admin`.

@tayormi and @jonddon please elaborate more on these. Can a user select their role at registration? If yes, does that mean a user can select an `Admin` role at registration?

**Comment by tayormi** [comment]
There will be a base Admin. Every user that registers on the platform is by default a Mentee. The Base admin can upgrade a user to a Mentor or Admin role.
A mentee becomes a mentor after completing some certain courses and tasks. The idea is to turn every mentee to a mentor as a way of giving back to the community.

**Comment by ofuochi** [comment]
Ok.

**Comment by ebenezer-code** [comment]
Please what languages do you guys use for back end here?
No offense please

**Comment by ofuochi** [comment]
We use Javascript

**Comment by ebenezer-code** [comment]
Pure js abi js library

**Comment by ebenezer-code** [comment]
Or framework

**Comment by ebenezer-code** [comment]
Or framework

**Comment by ofuochi** [comment]
Actually, a framework called [nestJs](https://nestjs.com/)

**Comment by ebenezer-code** [comment]
Ok..how about for the ui and frontend guys. 
I was invited early today

**Comment by ofuochi** [comment]
You can go over here for the [UI/UX designs](https://github.com/codeclannigeria/CodeClanUI) and here for the [frontend](https://github.com/codeclannigeria/codeclannigeria-frontend)

**Comment by ebenezer-code** [comment]
Kk
