### ISSUE TITLE
Temporarily Disable Token Registration

### ISSUE THREAD

**Issue by seunbayo** [codeclannigeria/codeclannigeria-backend#281]
We will be taking in more than a fire in this cohort 4 for the frontend track however we would want to disable registration on the portal so that when we don't want any more interns to register, they won't be able to register.
Apparently, we need a way to open and close registrations on the portal. 
Having an  _enable registration_ endpoint would be great for this where we can just pass in **true** or **false**

**Comment by ofuochi** [comment]
Should the `disable` feature happen for only a specific track or for the entire platform?

**Comment by tayormi** [comment]
> Should the `disable` feature happen for only a specific track or for the entire platform?

On a track would be great. Some tracks may be running concurrently.

**Comment by seunbayo** [comment]
Specific track

**Comment by tayormi** [comment]
Bump! Is there any update on this?

**Comment by ofuochi** [comment]
We'll get an update on this ASAP

**Comment by tayormi** [comment]
No update yet?

**Comment by tayormi** [comment]
Our cohort is starting. Please help!!!

**Comment by ofuochi** [comment]
@tayormi and @seunbayo 
Can this disabling happen at the point of login? The reason is, there's no way to tell what track a user is going to be in at the point of registering

**Comment by seunbayo** [comment]
Meaning users will be unable to register for a track at a point right?

**Comment by tayormi** [comment]
How about we just disable enrollment for a particular track?

**Comment by tayormi** [comment]
So if they want to enrol to Frontend for example, they won't be able to enrol

**Comment by ofuochi** [comment]
> How about we just disable enrollment for a particular track?

That's what I mean Sir

**Comment by ofuochi** [comment]
> Meaning users will be unable to register for a track at a point right?

Yes Sir
