### ISSUE TITLE
Add readme

### ISSUE THREAD

**Issue by ofuochi** [codeclannigeria/codeclannigeria-backend#3]
Add readme to project subfolders

**Comment by KarenEfereyan** [comment]
like the src and test folders, right?

**Comment by ofuochi** [comment]
Lol,
Add it to the root path

**Comment by ofuochi** [comment]
@KarenEfereyan I'll wait for your PR on this

**Comment by KarenEfereyan** [comment]
On it. There's no light now

**Comment by ofuochi** [comment]
Okay
