### ISSUE TITLE
[FEAT] Courses

### ISSUE THREAD

**Issue by CodewithKisha** [codeclannigeria/codeclannigeria-backend#32]
Courses are a series of lecture or lessons in a particular track.

It should contain the following:

Title - Title of the course (Html, Css, bootstrap, Javascript, e.t.c)
Description - Brief explanation of what the course contains.
Video - Tutorial Videos.
No of Enrollment - Number of Mentees/Users currently enrolled in the course.
Status - User should be able to resume from where he/she stopped in the course.
A Refresh Button - Clicking the refresh button will call the API again and re-fetch the video playlist.

An admin should be able to pass in title, description, image and then a YouTube playlist when creating a course.

**Comment by darellwest** [comment]
Unassigned?

**Comment by CodewithKisha** [comment]
Yeah I reassigned it to fortune

**Comment by tayormi** [comment]
@darellwest, do you want to take this up?
