### ISSUE TITLE
Track Registration

### ISSUE THREAD

**Issue by rammyblog** [codeclannigeria/codeclannigeria-backend#60]
**Is your feature request related to a problem? Please describe.**
There is no way to link a user to a track currently.

**Describe the solution you'd like**
An Api that allows a user to register for tracks.

**Comment by ofuochi** [comment]
Won't this be redundant? We already register for Tasks.

**Comment by rammyblog** [comment]
Getting a forbidden error each time I try even as I am authenticated.

**Comment by ofuochi** [comment]
That's because you're an Admin. Only Mentees can enrol for a track
