### ISSUE TITLE
Create User Interface For Web

### ISSUE THREAD

**Issue by tayormi** [codeclannigeria/codeclannigeria-backend#7]

**Comment by daegee** [comment]
I'm here, Can i join the UI design

**Comment by KarenEfereyan** [comment]
Sir, where are the asset files sir? So we get started

**Comment by tayormi** [comment]
> I'm here, Can i join the UI design

Yes you can.

**Comment by tayormi** [comment]
> Sir, where are the asset files sir? So we get started

I am still looking for a new one you can use. I'll upload one over soon.

**Comment by KarenEfereyan** [comment]
Please sir, can you do that soon?

**Comment by tayormi** [comment]
I uploaded a Figma file to the UI Design team already.

**Comment by KarenEfereyan** [comment]
I can't find it though

**Comment by daegee** [comment]
> I uploaded a Figma file to the UI Design team already.

I can't find the Figma file too

**Comment by tayormi** [comment]
Follow this conversation if you are part of the UI design team

https://github.com/orgs/codeclannigeria/teams/uidesign/discussions/1
