### ISSUE TITLE
Returning Data for POST requests 

### ISSUE THREAD

**Issue by rammyblog** [codeclannigeria/codeclannigeria-backend#76]
I need you to return a JSON object for Track Enrollment, Profile Edit.

**Comment by ofuochi** [comment]
is this a feat or a bug? I'm a little confused. Try to use the template while creating issues, make it a bit easier for me to understand

**Comment by rammyblog** [comment]
It is a feature

**Comment by ofuochi** [comment]
I'll return the `UserDTO` for Profile Edit. What object do you want me to return for Track Enrollment? Is there any need to return any object for track enrollment? I don't think. Once you call the endpoint and it returns 200, you know you're surely enrolled to the track.
