### ISSUE TITLE
Getting the stage of the mentee in a track

### ISSUE THREAD

**Issue by rammyblog** [codeclannigeria/codeclannigeria-backend#79]
**Is your feature request related to a problem? Please describe.**
If I hit the profile endpoint, I get the user tracks but I do not get the stage the user is in

**Describe the solution you'd like**
When I hit the profile endpoint, I should get the stage the user is currently

**Comment by ofuochi** [comment]
You can get the stages from ```/tracks​/{trackId}​/stages```

**Comment by rammyblog** [comment]
I want to know the right stage the user is on and not all stages associated with the track.

**Comment by rammyblog** [comment]
@ofuochi

**Comment by ofuochi** [comment]
Then we need a way to assign just a single stage. Currently, we can assign track.

@tayormi / @rammyblog  how do we assign a stage to a user?

**Comment by tayormi** [comment]
Hello @ofuochi, when a user enrols to a track, he is automatically enrolled to stage one.
When he completed all the task in stage one, on completion of the last tasks in stage one, he is automatically moved to the next stage.

**Comment by nskalu** [comment]
First, can you give me more context on tracks and stage, given i'm a user, what's the difference or relationship between both of them.  Secondly, Tope mentioned a user should be auto enrolled to a stage when they enrol to a track. has this been done? or should i make it a part of this issue?

CC @ofuochi  @tayormi
