### ISSUE TITLE
Send more details with the JWT

### ISSUE THREAD

**Issue by rammyblog** [codeclannigeria/codeclannigeria-backend#85]
**Is your feature request related to a problem? Please describe.**
I will have to hit the endpoint every time, if I need to get the track the user is enrolled in.

**Describe the solution you'd like**
Send the track the user is enrolled in and the current stage the user is in.

**Comment by ofuochi** [comment]
That can be gotten in the user endpoint. That sort of info shouldn't be in the JWT. JWT is purely for auth
