### ISSUE TITLE
Mentor's Endpoints

### ISSUE THREAD

**Issue by rammyblog** [codeclannigeria/codeclannigeria-backend#92]
**Is your feature request related to a problem? Please describe.**
There is currently no endpoints for the mentors

**Describe the solution you'd like**
An endpoint to list all the mentees assigned to a mentor, and when the mentee submits a task how the mentor will know for that particular mentee.

**Comment by ofuochi** [comment]
First, we need an endpoint to assign mentees to mentors. @rammyblog Please could you create an issue for this and the features you'd like it to have (to suite you use case)

**Comment by tayormi** [comment]
Mentors should be automatically assigned to a user when they enrolled in a track. It's not manual.

**Comment by ofuochi** [comment]
Is there a quota?. As in, how many Mentees per Mentor?

**Comment by tayormi** [comment]
We don't have a quote now. We can make it configurable. Our algorithm should automatically assign based on the available mentors. For example, if we have 5 mentors we will assign mentee to each one as mentees register.
