### ISSUE TITLE
Create an update profile endpoint to capture more user's details

### ISSUE THREAD

**Issue by tayormi** [codeclannigeria/codeclannigeria-backend#93]
**Is your feature request related to a problem? Please describe.**
We need to know more about the user when they sign up. We will use this data to give users offerings/opportunities in future.

**Describe the solution you'd like**
Add an update profile endpoint that allows user to enter.

***** User shouldn't be able to take any action until they've updated their profile.

1. First Name
2. Last name
3. City
4. Country
5. Gender (Male, Female, Prefer not to say).
6. Date of Birth
7. Phone Number
8. Profile Pic.

**Comment by ofuochi** [comment]
I was thinking we make it later when the user updates their profile. It's overwhelming to have to provide all of these details at registration.

**Comment by tayormi** [comment]
That's fine then. We have to make it mandatory though. We need that data. This is how we can pair them with recruiters in future.

**Comment by ofuochi** [comment]
So could you modify your req/feat to state this

**Comment by tayormi** [comment]
Alright
